version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    networks:
      - SmartRF

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - SmartRF

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    depends_on:
      - nodejs
    networks:
      - SmartRF

networks:
  SmartRF:
